name: Create environment
on: [push, workflow_dispatch]
env:
  RESOURCE_GROUP: Tahira1-rg
  LOCATION: westeurope
  TEMPLATE-FILE: web1.bicep
  SUBSCRIPTION-ID: ${{ secrets.subscriptionId }}
  WEBAPP-NAME: "az400yy-webapp-tahira00test"
  APP_LOCATION: "/" # location of your client code
  API_LOCATION: "api" # location of your api source code - optional
  APP_ARTIFACT_LOCATION: "build" # location of client code build output

jobs:
  create-environment:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Get token
      id: token
      run: |
        token=$(az staticwebapp secrets list --name ${{ env.WEBAPP_NAME }} --query properties.apiKey)
        echo "Deployment=$token" >> $GITHUB_ENV

    - name: Set Azure Static Web Apps API Token
      run: |
        deployment_token=${{ env.Deployment }}
        echo "Setting Azure Static Web Apps API token..."
        echo "azure_static_web_apps_api_token=$deployment_token" >> $GITHUB_ENV

    - name: Build And Deploy
      id: builddeploy
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ env.Deployment }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: ${{ env.APP_LOCATION }}
        api_location: ${{ env.API_LOCATION }}
        app_artifact_location: ${{ env.APP_ARTIFACT_LOCATION }}
