name: Create environment
on: [push, workflow_dispatch]
env:
  RESOURCE-GROUP: Tahira1-rg
  LOCATION: westeurope
  TEMPLATE-FILE: web1.bicep
  SUBSCRIPTION-ID: ${{ secrets.subscriptionId }}
  WEBAPP-NAME: az400yy-webapp-tahira00test
  APP_LOCATION: "/" # location of your client code
  API_LOCATION: "api" # location of your api source code - optional
  APP_ARTIFACT_LOCATION: "build" # location of client code build output

jobs:
  create-environment:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # - name: Azure CLI Create resource group  
    #   uses: Azure/cli@1.0.4
    #   with:
    #     inlineScript: az group create -n ${{ env.RESOURCE-GROUP }} -l ${{ env.LOCATION }}

    # - name: Deploy Bicep file
    #   uses: azure/arm-deploy@v1
    #   with:
        
    #     subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
    #     resourceGroupName: ${{ env.RESOURCE-GROUP }}
    #     template: web1.bicep
    #     parameters: 'name=${{ env.WEBAPP-NAME }} location=${{ env.LOCATION }}'
    #     # failOnStdErr: false  
      
    - name: Get token
      id: token
      run: | 
        token=$(az staticwebapp secrets list --name ${{ env.WEBAPP-NAME  }} --query properties.apiKey)
        echo "Deployment=$token" >> $GITHUB_ENV
        token=$(az staticwebapp secrets list --name ${{ env.WEBAPP-NAME  }} --query properties.apiKey)
        echo "Deployment_token1=$token" >> $GITHUB_OUTPUT

    - name: Get token output
      run: |  
        echo ${{ env.RESOURCE-GROUP }}
        echo "new token is"
        echo ${{ env.Deployment }} 
        echo "new token output is"
        echo ${{ steps.token.outputs.Deployment_token1 }}

    - name: Build And Deploy
      id: builddeploy
      uses: Azure/static-web-apps-deploy@v1
      with:
        # azure_static_web_apps_api_token: ${{ env.Deployment }} 
        azure_static_web_apps_api_token: "f6fde6ca968c99ce98651bd07bc70ee11c032471ebcfa0b1debbf5a5f66dc47b4-3efc36f9-2a5d-4138-be0a-14de9c3671d5003297006"
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        ###### Repository/Build Configurations - These values can be configured to match you app requirements. ######
        # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
        app_location: ${{ env.APP_LOCATION }}
        api_location: ${{ env.API_LOCATION }}
        app_artifact_location: ${{ env.APP_ARTIFACT_LOCATION }}
